### ISSUE TITLE
Andrew Peters - Code Review

### ISSUE THREAD

**Issue by APeters97** [ananyasingh7/Graphs#1]
https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Graph.java#L48-L56
this is a clever way to check if a node is a neighbor of another, but it would be better to combine your if and else if into one check. only return false if first is a neighbor of second and second is a neighbor of first. if someone were to hardcode one as a neighbor but not vice versa, this could cause an issue

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L9-L14
for this random graph, you don't add n random nodes to the graph, you always add specific nodes 0 through n-1

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L19-L21
this code could potentially generate the same 2 random numbers, so you would add an edge from a node to itself

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L51
you are covering the case of not returning the path if the destination node is not in the path, but the problem said to return null and not an empty array

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L66
for this if statement the and symbol should be &&, doing one & will throw an error

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L57-L84
your BFT looks good, but your code won't cover the case of if the graph contains any disconnected nodes

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L9-L26
for your random DAG, when you generate 2 random nodes to add an edge to you don't check to make sure the edge is not going backwards. this would create a cycle in the graph and a DAG is acyclic

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L12-L14
for this random DAG, you don't add n random nodes to the graph, you always add specific nodes 0 through n-1

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L19-L21
this could potentially generate the same random number, and so you would add an edge from a node to itself

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L54-L60
you could save memory space by just using one stack and making your helper method a void method

**Comment by ananyasingh7** [comment]
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Graph.java#L48-L56
> 
> 
> this is a clever way to check if a node is a neighbor of another, but it would be better to combine your if and else if into one check. only return false if first is a neighbor of second and second is a neighbor of first. if someone were to hardcode one as a neighbor but not vice versa, this could cause an issue
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L9-L14
> 
> 
> for this random graph, you don't add n random nodes to the graph, you always add specific nodes 0 through n-1
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L19-L21
> 
> 
> this code could potentially generate the same 2 random numbers, so you would add an edge from a node to itself
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L51
> 
> 
> you are covering the case of not returning the path if the destination node is not in the path, but the problem said to return null and not an empty array
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L66
> 
> 
> for this if statement the and symbol should be &&, doing one & will throw an error
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L57-L84
> 
> 
> your BFT looks good, but your code won't cover the case of if the graph contains any disconnected nodes
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L9-L26
> 
> 
> for your random DAG, when you generate 2 random nodes to add an edge to you don't check to make sure the edge is not going backwards. this would create a cycle in the graph and a DAG is acyclic
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L12-L14
> 
> 
> for this random DAG, you don't add n random nodes to the graph, you always add specific nodes 0 through n-1
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L19-L21
> 
> 
> this could potentially generate the same random number, and so you would add an edge from a node to itself
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L54-L60
> 
> 
> you could save memory space by just using one stack and making your helper method a void method

"for this random graph, you don't add n random nodes to the graph, you always add specific nodes 0 through n-1" DISAGREE: That's what the function is doing, maybe the comment confused you?
"for your random DAG, when you generate 2 random nodes to add an edge to you don't check to make sure the edge is not going backward. this would create a cycle in the graph and a DAG is acyclic" Major Issue: I agree and this is something I am going to fix before I turn in the assignment. I want to finish everything else up first.
"you could save memory space by just using one stack and making your helper method a void method" DISAGREE: Yes I could save memory space but the way my mDFS is designed, by the helper ALWAYS needs to return the stack so I can return the order of the DFS.

Everything else I agree on and fixed and is addressed here: https://github.com/ananyasingh7/Graphs/commit/770eb9d2b938dc2e99596ed2709722710cb13227
