### ISSUE TITLE
Code Review - sl755

### ISSUE THREAD

**Issue by aerCreativity** [ananyasingh7/Graphs#2]
Yo. Here's a code review.

No roasting needed, even though this is java.

**Comment by aerCreativity** [comment]
I strongly recommend that you do not use an empty main function, even if you're not intending on using the main.
Even better, though, would be if you used your main function to test all of your code.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L28

**Comment by aerCreativity** [comment]
I strongly recommend taking your Test file and turning that into your Main.java for ThankUVertext. It's an easy solution for this issue and the previous one.

https://github.com/ananyasingh7/Graphs/blob/master/ThankUVertext/Test.java

I'd also like to point out the strange comments numbered "0, 1, 2, 3, 4, 5, 6" which give no clear direction.
Where the 4,5,6 are would be a great spot to show what you're attempting to Test as well.

**Comment by aerCreativity** [comment]
Slight convenience to add here would be to change the ArrayList into a HashSet. This allows your search time to turn from O(n) to O(1) without changing too many different things. It'd also help a lot if you intended on adding the ability to remove nodes.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Node.java#L10

**Comment by aerCreativity** [comment]
In your ThankUVertext/DirectedGraph.java, there's more code which lacks comments.

In addition, I'd recommend staying away from crude and potentially offensive language in comments.
https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/DirectedGraph.java#L71
Additionally, for that line's comment, you may want to replace the syntax with something less ambiguous.

**Comment by aerCreativity** [comment]
I'm curious where this dictionary() is being used. This method certainly would benefit from a comment which describes what it's for, and why you're not storing the adjacencies in a list or a matrix.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/DirectedGraph.java#L63

**Comment by aerCreativity** [comment]
Appreciate the shoutouts, but it's not helpful for others (random people who read github repos) if you comment like this. ^^

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L12

**Comment by aerCreativity** [comment]
A strong recommendation for you to clean up your commented out debug statements.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L20

**Comment by aerCreativity** [comment]
This is a big and very important loop and deserves some commenting to explain just how important it is.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L25

**Comment by aerCreativity** [comment]
There's plenty of blank space here. It looks like there might've been some debug/a main function here, but it's a great idea to clean up your code the same way you'd clean up and pretty up an essay.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/TopSort.java#L79

**Comment by aerCreativity** [comment]
I believe that this upload script isn't really too necessary to put into your program.
You can use a .gitignore file to ignore the bash files.

https://github.com/ananyasingh7/Graphs/blob/master/upload.sh

**Comment by ananyasingh7** [comment]
> I strongly recommend that you do not use an empty main function, even if you're not intending on using the main.
> Even better, though, would be if you used your main function to test all of your code.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/ThankUVertext/Main.java#L28

OK - Addressed in: https://github.com/ananyasingh7/Graphs/commit/05277f32f76d3926f837f2a4da2bbe005f889164

**Comment by ananyasingh7** [comment]
> I strongly recommend taking your Test file and turning that into your Main.java for ThankUVertext. It's an easy solution for this issue and the previous one.
> 
> https://github.com/ananyasingh7/Graphs/blob/master/ThankUVertext/Test.java
> 
> I'd also like to point out the strange comments numbered "0, 1, 2, 3, 4, 5, 6" which give no clear direction.
> Where the 4,5,6 are would be a great spot to show what you're attempting to Test as well.

Will remove Test once submitted

**Comment by ananyasingh7** [comment]
> I strongly recommend taking your Test file and turning that into your Main.java for ThankUVertext. It's an easy solution for this issue and the previous one.
> 
> https://github.com/ananyasingh7/Graphs/blob/master/ThankUVertext/Test.java
> 
> I'd also like to point out the strange comments numbered "0, 1, 2, 3, 4, 5, 6" which give no clear direction.
> Where the 4,5,6 are would be a great spot to show what you're attempting to Test as well.

OK - Addressed in: 05277f3

**Comment by ananyasingh7** [comment]
> 
> Additionally, for that line's comment, you may want to replace the syntax with something less ambiguous.

OK - Addressed in: 05277f3

**Comment by ananyasingh7** [comment]
Everything is addressed in: 05277f3

Thanks for the review
