### ISSUE TITLE
Code Review - Siddharth Patel

### ISSUE THREAD

**Issue by Syzygy05** [ananyasingh7/Graphs#3]
You're probably running into situations where the same node is being randomly generated for graphs that only have a few nodes. You could increase the bound. 

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L18-L22

**Comment by Syzygy05** [comment]
Integrate the size into the loop declaration (like in the condition). Makes for cleaner code.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L34-L35

**Comment by Syzygy05** [comment]
I recommend adding comments so other code reviewers/group members or even you can easily understand what is happening with a glance if you come back to the code weeks from now.

**Comment by Syzygy05** [comment]
I may have just missed it, but where are you keeping track of your edge connection/adjacency list/matrix?

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Graph.java#L8-L10

**Comment by Syzygy05** [comment]
This was a really good idea to implement into helper functions. I've seen some code that did this within the algorithm when needed rather than just creating a function that does this can calling when necessary. 

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Graph.java#L40-L63

**Comment by Syzygy05** [comment]
Use a while loop that loops through a list of nodes that you want to add edges to. Reduces the amount of repetitive code.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Test.java#L19-L45

**Comment by Syzygy05** [comment]
Add some whitespace between graphs so it is easier to read.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Test.java#L51-L80

**Comment by Syzygy05** [comment]
I think you meant it takes an iterative approach as opposed to a recursive method.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L28

**Comment by Syzygy05** [comment]
Redundant creation of a variable, waste space.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L35

**Comment by Syzygy05** [comment]
The time complexity of this is very large, there may be a more efficient way of doing this.

https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L91-L107

**Comment by ananyasingh7** [comment]
> I may have just missed it, but where are you keeping track of your edge connection/adjacency list/matrix?
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Graph.java#L8-L10

DISAGREE: my adjacency list is in node class

**Comment by ananyasingh7** [comment]
> Use a while loop that loops through a list of nodes that you want to add edges to. Reduces the amount of repetitive code.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Test.java#L19-L45

DISAGREE: This is an example graph where nodes are not connected numerically or in order, so I can't use a while loop.

**Comment by ananyasingh7** [comment]
> Redundant creation of a variable, waste space.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L35

DISAGREE: need the variable as my flag to see if I can return the path or not.

**Comment by ananyasingh7** [comment]
> The time complexity of this is very large, there may be a more efficient way of doing this.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/GraphSearch.java#L91-L107

DISAGREE: There might be a way more efficient way but I honestly can't think of it.

**Comment by ananyasingh7** [comment]
> You're probably running into situations where the same node is being randomly generated for graphs that only have a few nodes. You could increase the bound.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L18-L22

OK - addressed in: https://github.com/ananyasingh7/Graphs/commit/ddcb66440942554ac9017b239db3d978292f437e

**Comment by ananyasingh7** [comment]
> Integrate the size into the loop declaration (like in the condition). Makes for cleaner code.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Main.java#L34-L35

OK - addressed in: https://github.com/ananyasingh7/Graphs/commit/ddcb66440942554ac9017b239db3d978292f437e

**Comment by ananyasingh7** [comment]
> Add some whitespace between graphs so it is easier to read.
> 
> https://github.com/ananyasingh7/Graphs/blob/d603883f9ee53fb94e29e195d256059e8531218e/TraverseThisTown/Test.java#L51-L80

OK - addressed in: https://github.com/ananyasingh7/Graphs/commit/ddcb66440942554ac9017b239db3d978292f437e
